name: Build Docker Image and pust to Dockerhub

on:
  push:
    branches: [ "main" ]  # Change to "master" if your branch is named master
  # Keep this if you still want to be able to click "Run" manually sometimes
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  docker-image-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load Project Configuration
        run: cat docker.env >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_REPO }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_REPO }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-eks:
    needs: docker-image-creation  # Waits for Job 1 to succeed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Load Project Configuration
        run: cat docker.env >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use the role ARN from your secret
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ca-central-1
          # session-name is optional but good for debugging logs in CloudTrail
          role-session-name: GitHubActionsSession

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ca-central-1

      - name: Deploy Manifests
        env:
          IMAGE_URI: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_REPO }}:latest
        run: |
          aws eks create-pod-identity-association --cluster-name ${{ env.EKS_CLUSTER_NAME }} --namespace default --service-account web-service-account --role-arn arn:aws:iam::541804384520:role/eks-pod-identity-web-role --region ca-central-1 || echo "Association already exists"
          sudo apt-get install -y gettext-base
          for file in eksfiles/*.yml; do envsubst < "$file" | kubectl apply -f -; done
          kubectl rollout restart deployment/web-deployment